apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: db-where-for-dinner
  namespace: workloads
spec:
  classRef:
    name: db-crossplane-where-for-dinner
  parameters:
    storageGB: 1
    serviceNamespace: service-instances
